--LIKE OPERATOR IS USED TO SEARCH FOR A SPECIFIC PATTERN IN COLUMN

USE QUERIES;

CREATE TABLE STUDENTS
(
ID INT,
NAME VARCHAR(30),
CODE INT,
CITY VARCHAR (30)
);

INSERT INTO STUDENTS VALUES (01,'soumya',761105, 'polasara'),
							(02,'sagar',769824, 'barhempur'),
							(03,'kishan',762983, 'sorada'),
							(04,'ranjeet',761534, 'bhubaneswar'),
							(05,'tarun',765491, 'palasa');
SELECT * FROM students;
							
--S% MEANS ANY VALUE THAT STARTS WITH S
SELECT * FROM STUDENTS
WHERE NAME LIKE 'S%';

--%B MEANS ANY VALUE THAT ENDS WITH B
SELECT * FROM STUDENTS
WHERE NAME LIKE '%T';

--%AB% MEANS ANY VALUE THAT HAVE 'AB' IN ANY POSITION
SELECT * FROM STUDENTS
WHERE city LIKE '%la%';

--_A% MEANS ANY VALUE THAT HAVE 'I' IN 2nd POSITION
SELECT * FROM STUDENTS
WHERE NAME LIKE '_i%';

--A%B MEANS ANY VALUE THAT HAVE 'k' IN 1st POSITION AND 'n' IN LAST POSITION
SELECT * FROM STUDENTS
WHERE NAME LIKE 'k%n';

--A__% MEANS ANY VALUE THAT HAVE 't' IN 1st POSITION AND SHOULD BE ATLEAST 3 CHARACTERS IN LENGTH
SELECT * FROM STUDENTS
WHERE NAME LIKE 'T__%';


