-- DELETE, TRUNCATE, DROP AND AUTO INCRIMENT

USE QUERIES;

CREATE TABLE STUDZ(
ID INT,
NAME VARCHAR(30),
marks INT
);

INSERT INTO STUDZ VALUES (1,'soumya',100),
						 (2,'sameer',200),
						 (3,'sagar',300),
						 (4,'himanshu',400),
						 (5,'tarun',500),
						 (6,'kishan',600);

SELECT * FROM STUDZ;


--DELETE: IT DELETES A SPECIFIC RECORD FROM THE TABLE, ROLL BACK IS POSSIBLE
-- DELETES THE ENTIRE ROW HAVING ID = 1
DELETE FROM STUDZ
WHERE ID = 1;
SELECT * FROM STUDZ;

--USING ROLLBACK


--TRUNCATE: IT DELETES ALL THE RECORD FROM THE TABLE BUT NOT THE STRUCTURE,CANNOT BE ROLLBACK
TRUNCATE TABLE STUDZ
SELECT * FROM STUDZ;

--DROP: IT DELETES BOTH THE DATA AND TABLE STRUCTURE, CANNOT BE ROLL BACK


SELECT * FROM STUDZ;

--AUTO INCRIMENT
--CREATE TABLE TABLENAME(COLUMN NAME DATATYPE IDENTITY(M,N) CONSTRAINTS); WHERE M=  INITIAL NUMBER AND N= ORDER

CREATE TABLE TEACHER
(
ID INT IDENTITY(1,1),
NAME VARCHAR(30),
SALARY INT
);

INSERT INTO TEACHER VALUES ('soumya',100),
						   ('sameer',200),
						   ('sagar',300),
						   ('himanshu',400),
						   ('tarun',500),
						   ('kishan',600);
SELECT * FROM TEACHER;

