--SET OPERATIONS

CREATE TABLE CSE
(
ID int,
NAME varchar (20),
SALARY int
);

INSERT INTO CSE VALUES (1,'MANOJ',50000),
					   (2,'CHANDAN',45000),
					   (3,'BHAVANI',30000),
					   (4,'SUBHENDU',35000),
					   (5,'BITU',25000);


CREATE TABLE ECE
(
ID int,
NAME varchar (20),
SALARY int
);

INSERT INTO ECE VALUES (1,'SANDIP',50000),
					   (2,'BINOD',30000),
					   (3,'SURYA',40000),
					   (4,'SUBHENDU',35000),				--DROP TABLE ECE;
					   (5,'SUMAN',34000);

SELECT * FROM ECE;
SELECT * FROM CSE;


--UNION 

SELECT * FROM CSE
UNION
SELECT * FROM ECE;

--UNION ALL

SELECT * FROM CSE
UNION ALL
SELECT * FROM ECE;

--INTERSECT

SELECT * FROM CSE
INTERSECT
SELECT * FROM ECE;

--EXCEPT

SELECT * FROM CSE
EXCEPT
SELECT * FROM ECE;