--SQL AGGRIGATE FUNCTIONS

CREATE TABLE company
(
ID int,
NAME varchar(20),
DEPT varchar(20),
SALARY int
);

INSERT INTO company VALUES (1,'NOBITA','CSE',50000),
						   (2,'SIZUKA','ECE',45000),
						   (3,'GEEAN','MECH',30000),
						   (4,'SUNIO','CSE',45000),
						   (5,'SHINCHAN','EEE',36000),
						   (6,'DEKISUGI','CIVIL',NULL);

SELECT * FROM company;

--SUM AGGRIGATE FUNCTION
------------------------TO FIND TOTAL VALUE OF A COLUMN (INT DATA TYPE)

SELECT SUM (SALARY) AS TOTAL_SALARY FROM company;

--COUNT AGGRIGATE FUNCTION
--------------------------TO FIND NUMBER OF ROWS IN A TABLE

SELECT COUNT (*) AS TOTAL_ROWS FROM company;

--TO FIND NUMBER OF ROWS IN A COLUMN

SELECT COUNT (SALARY) AS TOTAL_ROWS FROM company;

--TO FIND NUMBER OF UNIQUE VALUES IN A COLUMN

SELECT COUNT (DISTINCT(SALARY)) AS UNIQUE_SALARY FROM company;

--AVG AGGRIGATE FUNCTION
------------------------TO FIND THE AVERAGE VALUE OF A COLUMN (INT DATA TYPE)

SELECT AVG (SALARY) AS AVG_SALARY FROM company;

--MAX AGGRIGATE FUNCTION
------------------------TO FIND MAXIMUM VALUE OF A COLUMN (INT DATA TYPE)

SELECT MAX (salary) AS MAX_SALARY FROM company;

--MIN AGGRIGATE FUNCTION
------------------------TO FIND MINIMUM VALUE OF A COLUMN (INT DATA TYPE)

SELECT MIN (salary) AS MAX_SALARY FROM company;