--SQL GROUP BY & HAVING CLAUSE

CREATE TABLE CUSTOMERS
(
ID int,
NAME varchar(20),
GENDER varchar(10),
SALES int,
CITY varchar(10)
);

INSERT INTO CUSTOMERS VALUES (1,'RAM','MALE',10000,'HYDERABAD'),
							 (2,'SHAM','MALE',20000,'VIZAG'),
							 (3,'SITA','FEMALE',15000,'KARNATAKA'),
							 (4,'GEETHA','FEMALE',10000,'DELHI'),
							 (5,'MANOJ','MALE',11000,'MUMBAI'),
							 (6,'KUMAR','MALE',15000,'CHINNAI'),
							 (7,'JHON','MALE',14000,'KOLKATA'),
							 (8,'RITA','FEMALE',16000,'GOA');

SELECT * FROM CUSTOMERS; 

SELECT SUM(SALES) AS TOTAL_SALES FROM CUSTOMERS;

SELECT CITY,SUM(SALES) AS TOTAL_SALES FROM CUSTOMERS GROUP BY CITY;

SELECT GENDER,SUM(SALES) AS GENDER_WISE_SALES FROM CUSTOMERS GROUP BY GENDER;

SELECT CITY,SUM(SALES) AS TOTAL_SALES FROM CUSTOMERS GROUP BY CITY HAVING SUM(SALES)>12000;

SELECT ID,SUM(SALES) AS TOTAL_SALES FROM CUSTOMERS where ID>2 GROUP BY ID HAVING SUM(SALES)>8000;


