--stored procedures

CREATE TABLE EMP_Details
(
ID INT identity (1,1),
NAME VARCHAR(20),
GENDER VARCHAR(10),
DEPT_ID INT
);

INSERT INTO EMP_Details VALUES ('RAM','MALE',1),
							   ('SHAM','MALE',1),
							   ('SITA','FEMALE',3),
							   ('GITA','FEMALE',2),
							   ('REETA','FEMALE',3),
							   ('GOPAL','MALE',2),
							   ('BABITA','FEMALE',1),
							   ('SANGEETA','FEMALE',2),
							   ('SHYAM','MALE',1),
							   ('GAYATRI','FEMALE',2);

SELECT * FROM EMP_Details;


--STORED PROCEDURE

CREATE PROCEDURE SPGetEmpNameAndDept
CREATE PROC SPGetEmpNameAndDept
AS
BEGIN
	SELECT NAME, DEPT_ID FROM EMP_Details;
END;

EXECUTE SPGetEmpNameAndDept;
EXEC SPGetEmpNameAndDept;
SPGetEmpNameAndDept;


--STORED PROCEDURE WITH INPUT PARAMETERS (@PREFIX)

CREATE PROCEDURE SPGetEmpByGenderAndDept 
@GENDER VARCHAR(20),
@DEPT_ID INT
AS
BEGIN
	SELECT NAME, GENDER, DEPT_ID FROM EMP_Details
		WHERE GENDER = @GENDER AND DEPT_ID = @DEPT_ID
END;

EXECUTE SPGetEmpByGenderAndDept @GENDER = 'male', @DEPT_ID = 1;


--ALTER STATEMENT (WE CAN MODIFY OUR DATA)

ALTER PROCEDURE SPGetEmpNameAndDept
AS
BEGIN
SELECT NAME, GENDER FROM EMP_Details 
WHERE GENDER = 'FEMALE';
END;

EXECUTE SPGetEmpNameAndDept;


--TO SEE THE SP IN GRAPHICAL VIEW

SP_HELPTEXT'SPGetEmpNameAndDept';


--ENCRYPTION ( TO PROTECT OUR DATA IN ENCRYPTED FORMAT)

ALTER PROCEDURE SPGetEmpNameAndDept
WITH ENCRYPTION
AS
BEGIN
SELECT NAME, GENDER FROM EMP_Details
WHERE GENDER = 'FEMALE';
END;


--DROP

DROP PROCEDURE SPGetEmpNameAndDept;
DROP PROCEDURE SPGetEmpByGenderAndDept;